// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddTimetable(name: string, src: string): $CancellablePromise<void> {
    return $Call.ByID(1659307509, name, src);
}

export function DeleteTimetable(id: string): $CancellablePromise<void> {
    return $Call.ByID(2365927407, id);
}

export function GetTimetables(): $CancellablePromise<$models.Timetable[]> {
    return $Call.ByID(1890721389).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.Timetable.createFrom;
const $$createType1 = $Create.Array($$createType0);
