// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as DBService from "./dbservice.js";
export {
    DBService
};

export {
    Timetable
} from "./models.js";
