// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Timetable {
    "Id": string;
    "Name": string;
    "Src": string;

    /** Creates a new Timetable instance. */
    constructor($$source: Partial<Timetable> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = "";
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Src" in $$source)) {
            this["Src"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Timetable instance from a string or object.
     */
    static createFrom($$source: any = {}): Timetable {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Timetable($$parsedSource as Partial<Timetable>);
    }
}
